feat: added GET method to trust_mark_status endpoint
italia/spid-cie-oidc-django pull request #310
Opened 2024-02-29 10:38 UTC by mattebit

+ fix: excluded trust_mark_status endpoint from Django CSRF protection

fixes #308

2024-02-29 15:24 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +    sub = ""
```suggestion
    sub = params.get("sub", "")
```

2024-02-29 15:25 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +
```suggestion
```

2024-02-29 15:26 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +    else:
if not request.GET or request.POST:

2024-02-29 15:30 UTC, peppelinux requested changes
first revision round

2024-02-29 15:30 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +    else:
```suggestion
    if not request.GET or request.POST:
```

2024-02-29 15:30 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +        return JsonResponse(failed_data)
```suggestion
```

2024-02-29 15:30 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +    elif params.get("trust_mark", ""):
```suggestion
    if request.POST.get("trust_mark", ""):
```

2024-03-01 16:59 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +    _id = request.POST.get("trust_mark_id) or request.GET.get("trust_mark_id", None)
```suggestion
    _id = request.POST.get("trust_mark_id") or request.GET.get("trust_mark_id", None)
```

2024-03-01 17:01 UTC, peppelinux requested changes

2024-03-01 17:01 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +    if request.POST.get("trust_mark", ""):
```suggestion
    _tm = request.POST.get("trust_mark", None)
    if _tm:
```

2024-03-01 17:01 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
> +            payload = unpad_jwt_payload(params["trust_mark"])
```suggestion
            unpad_jwt_head(_tm)
            payload = unpad_jwt_payload(_tm)
```

2024-03-01 17:01 UTC, peppelinux commented on spid_cie_oidc/authority/views.py
>              _id = payload.get("id", "")
```suggestion
            sub = payload["sub"]
            _id = payload["id"]
```

2024-03-01 17:02 UTC, peppelinux commented
second round of revision

it needs further tests

2024-03-01 17:54 UTC, peppelinux commented on spid_cie_oidc/authority/tests/test_02_trust_anchor_intermediary.py
> +                "trust_mark_id": self.rp_assigned_profile.profile.profile_id,
teoricamente questa è una retrocompatiblità che dobbiamo gestire, dobbiamo gestire sia id che trust_mark_id

e lo so.

2024-03-04 09:38 UTC, mattebit commented on spid_cie_oidc/authority/tests/test_02_trust_anchor_intermediary.py
> +                "trust_mark_id": self.rp_assigned_profile.profile.profile_id,
ok, allora vedo di permettere entrambe le versioni

2024-03-11 08:35 UTC, merged